# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# boundary_fromgis.py
# Created on: 2015-10-26 15:54:24.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
ua_lehd_acs_1 = "ua_lehd_acs_1"
ua_lehd_acs_1__2_ = ua_lehd_acs_1
tl_2010_06_place10 = "tl_2010_06_place10"
tl_2010_06_place10_Layer = "tl_2010_06_place10_Layer"
place_line_hold_shp = "L:\\Research\\Resurgence\\Working Files\\Place Dissolve\\place_line_hold.shp"
boundary_tracts_hold_shp = "L:\\Research\\Resurgence\\Working Files\\Boundary\\boundary_tracts_hold.shp"

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(tl_2010_06_place10, tl_2010_06_place10_Layer, "\"NAME10\" = 'Los Angeles'", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;STATEFP10 STATEFP10 VISIBLE NONE;PLACEFP10 PLACEFP10 VISIBLE NONE;PLACENS10 PLACENS10 VISIBLE NONE;GEOID10 GEOID10 VISIBLE NONE;NAME10 NAME10 VISIBLE NONE;NAMELSAD10 NAMELSAD10 VISIBLE NONE;LSAD10 LSAD10 VISIBLE NONE;CLASSFP10 CLASSFP10 VISIBLE NONE;PCICBSA10 PCICBSA10 VISIBLE NONE;PCINECTA10 PCINECTA10 VISIBLE NONE;MTFCC10 MTFCC10 VISIBLE NONE;FUNCSTAT10 FUNCSTAT10 VISIBLE NONE;ALAND10 ALAND10 VISIBLE NONE;AWATER10 AWATER10 VISIBLE NONE;INTPTLAT10 INTPTLAT10 VISIBLE NONE;INTPTLON10 INTPTLON10 VISIBLE NONE")

# Process: Feature To Line
arcpy.FeatureToLine_management("tl_2010_06_place10_Layer", place_line_hold_shp, "", "ATTRIBUTES")

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(ua_lehd_acs_1, "WITHIN_A_DISTANCE", place_line_hold_shp, "1 Miles", "NEW_SELECTION", "NOT_INVERT")

# Process: Copy Features
arcpy.CopyFeatures_management(ua_lehd_acs_1__2_, boundary_tracts_hold_shp, "", "0", "0", "0")

