# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# def_cc.py
# Created on: 2014-05-13 10:23:47.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
urban_area_tracts_2 = "urban_area_tracts_2"
uat_cen_cluster = "uat_cen_cluster"
uat_cen_cluster__2_ = "uat_cen_cluster"
urban_area_lehd_join_2 = "urban_area_lehd_join_2"
urban_area_lehd_join_2__3_ = "urban_area_lehd_join_2"
uat_cen_cluster__4_ = "uat_cen_cluster"
uat_cen_point = "uat_cen_point"
uat_cen_point_shp = "C:\\Users\\Matthew\\Desktop\\ECON\\Research\\Urban\\Papers\\City Center Resurgence\\GIS\\Working Files\\Output\\uat_cen_point.shp"

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(urban_area_lehd_join_2, "WITHIN_A_DISTANCE", uat_cen_point, "2 Miles", "NEW_SELECTION")

# Process: Feature To Point
arcpy.FeatureToPoint_management(uat_cen_cluster__2_, uat_cen_point_shp, "CENTROID")

# Process: Select Layer By Location (2)
arcpy.SelectLayerByLocation_management(urban_area_lehd_join_2__3_, "WITHIN", uat_cen_cluster__4_, "", "NEW_SELECTION")

