# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# proj_cal.py
# Created on: 2014-04-28 15:29:38.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
import sys

def id_gen(STATE, COUNTY, TRACT):
    if len(TRACT) < 6:
          return STATE+COUNTY+TRACT+"00"
    else:
          return STATE+COUNTY+TRACT
		  
#states = ["AL", "AK", "AL", "AR", "AZ", "CO", "FL", "GA", "IA", "ID", "IL", "IN", "KS"\
          #, "KY", "LA", "MA", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH"\
		  #, "NM", "NV", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT"\
		  #s, "WA", "WI", "WV", "WY"]


states = ["DE"]
		  
for s in states:

		print s
		
		tracts = "C:\\Users\\Matthew\\Desktop\\ECON\\Research\\Urban\Papers\\City Center Resurgence\\GIS\\2000\\"+s+"_tracts_00.shp"
		  
		print "- Add Area Field"
		# Process: Add Field
		arcpy.AddField_management(tracts, "CTIDFP00", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

		print "- Compute Area"
		# Process: Calculate Field
		arcpy.CalculateField_management(tracts, "CTIDFP00", "id_gen(!STATE!,!COUNTY!,!TRACT!)", "PYTHON_9.3")


		
print "'MERICA, FUCK YEA!"		  
		  
