# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# merge_fill.py
# Created on: 2014-04-28 15:03:06.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
CT_tracts_12 = "CT_tracts_12"
NY_tracts_12 = "NY_tracts_12"
NJ_tracts_12 = "NJ_tracts_12"
NY_NJ_CT_tracts_shp = "C:\\Users\\Matthew\\Desktop\\ECON\\Research\\Urban\\Papers\\City Center Resurgence\\GIS\\Working Files\\NY_NJ_CT_tracts.shp"

# Process: Merge
arcpy.Merge_management("CT_tracts_12;NY_tracts_12;NJ_tracts_12", NY_NJ_CT_tracts_shp, "STATEFP \"STATEFP\" true true false 2 Text 0 0 ,First,#,CT_tracts_12,STATEFP,-1,-1,NY_tracts_12,STATEFP,-1,-1,NJ_tracts_12,STATEFP,-1,-1;COUNTYFP \"COUNTYFP\" true true false 3 Text 0 0 ,First,#,CT_tracts_12,COUNTYFP,-1,-1,NY_tracts_12,COUNTYFP,-1,-1,NJ_tracts_12,COUNTYFP,-1,-1;TRACTCE \"TRACTCE\" true true false 6 Text 0 0 ,First,#,CT_tracts_12,TRACTCE,-1,-1,NY_tracts_12,TRACTCE,-1,-1,NJ_tracts_12,TRACTCE,-1,-1;GEOID \"GEOID\" true true false 11 Text 0 0 ,First,#,CT_tracts_12,GEOID,-1,-1,NY_tracts_12,GEOID,-1,-1,NJ_tracts_12,GEOID,-1,-1;NAME \"NAME\" true true false 7 Text 0 0 ,First,#,CT_tracts_12,NAME,-1,-1,NY_tracts_12,NAME,-1,-1,NJ_tracts_12,NAME,-1,-1;NAMELSAD \"NAMELSAD\" true true false 20 Text 0 0 ,First,#,CT_tracts_12,NAMELSAD,-1,-1,NY_tracts_12,NAMELSAD,-1,-1,NJ_tracts_12,NAMELSAD,-1,-1;MTFCC \"MTFCC\" true true false 5 Text 0 0 ,First,#,CT_tracts_12,MTFCC,-1,-1,NY_tracts_12,MTFCC,-1,-1,NJ_tracts_12,MTFCC,-1,-1;FUNCSTAT \"FUNCSTAT\" true true false 1 Text 0 0 ,First,#,CT_tracts_12,FUNCSTAT,-1,-1,NY_tracts_12,FUNCSTAT,-1,-1,NJ_tracts_12,FUNCSTAT,-1,-1;ALAND \"ALAND\" true true false 14 Double 0 14 ,First,#,CT_tracts_12,ALAND,-1,-1,NY_tracts_12,ALAND,-1,-1,NJ_tracts_12,ALAND,-1,-1;AWATER \"AWATER\" true true false 14 Double 0 14 ,First,#,CT_tracts_12,AWATER,-1,-1,NY_tracts_12,AWATER,-1,-1,NJ_tracts_12,AWATER,-1,-1;INTPTLAT \"INTPTLAT\" true true false 11 Text 0 0 ,First,#,CT_tracts_12,INTPTLAT,-1,-1,NY_tracts_12,INTPTLAT,-1,-1,NJ_tracts_12,INTPTLAT,-1,-1;INTPTLON \"INTPTLON\" true true false 12 Text 0 0 ,First,#,CT_tracts_12,INTPTLON,-1,-1,NY_tracts_12,INTPTLON,-1,-1,NJ_tracts_12,INTPTLON,-1,-1")

