# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# redefine_xy.py
# Created on: 2015-12-18 15:05:59.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
uat_cen_point_0 = "uat_cen_point_0"
uat_cen_point = "C:\\Users\\mmiller\\Documents\\ArcGIS\\Default.gdb\\uat_cen_point"
uat_cen_point__2_ = uat_cen_point

# Process: Project
out_gcs = arcpy.SpatialReference('WGS_1984')
arcpy.Project_management(uat_cen_point_0, uat_cen_point, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "WGS_1984_(ITRF00)_To_NAD_1983", "PROJCS['NAD_1983_UTM_Zone_18N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-75.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "NO_PRESERVE_SHAPE", "")

# Process: Add XY Coordinates
arcpy.AddXY_management(uat_cen_point)

