# Matt Miller, UCLA 14S
# ---------------------------------------------------------------------------
# Name: urban_tracts.py
# Created on: 2014-04-10 16:50:48.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: (general) takes collection of larger area (MSAs, urban areas, states)
# selects relevant ones, and keeps smaller units within (e.g. census tracts)
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import sys

#Overwriting allowed
arcpy.env.overwriteOutput = True

#Working Directory
arcpy.env.workspace = "C:\\Users\\Matthew\\Desktop\\ECON\\Research\\Urban\\Papers\\City Center Resurgence\\GIS\\Working Files\\Output\\"

#Directories

#Inputs

state_10 = "C:\\Users\\Matthew\\Desktop\\ECON\\Research\\Urban\\Papers\\City Center Resurgence\\GIS\\urban_area_2010\\states_2010\\"
tract_12 = "C:\\Users\\Matthew\\Desktop\\ECON\\Research\\Urban\\Papers\\City Center Resurgence\\GIS\\2012\\" 
urban_10 = "C:\\Users\\Matthew\\Desktop\\ECON\\Research\\Urban\\Papers\\City Center Resurgence\\GIS\\urban_area_2010\\"

# Local variables:

urban_areas_2010_shp = urban_10 + "urban_areas_2010.shp"
PA_tracts_12 = tract_12 + "PA_tracts_12.shp"
DE_tracts = tract_12 + "DE_tracts.shp"
MD_tracts_12 = tract_12 + "MD_tracts_12.shp"
NJ_tracts_12 = tract_12 + "NJ_tracts_12.shp"
us_states_2010 = state_10 + "us_states_2010.shp"
urban_area = "urban_area"
state_tracts_union_shp = "state_tracts_union.shp"
state_tracts_clip_shp = "state_tracts_clip.shp"
urban_area_tracts_shp = "urban_area_tracts.shp"

##Geoprocessing#########################################################
try:
		print "Union for Multi-state Areas"
		# Process: Union
		arcpy.Union_analysis([PA_tracts_12, DE_tracts, MD_tracts_12, NJ_tracts_12], state_tracts_union_shp, "ALL", "", "GAPS")

		print "State Clip"
		# Process: Clip
		arcpy.Clip_analysis(state_tracts_union_shp, us_states_2010, state_tracts_clip_shp, "")

		print "Limit to Relevant Area"
		# Process: Make Feature Layer
		arcpy.MakeFeatureLayer_management(urban_areas_2010_shp, urban_area, "\"NAME10\" = 'Baltimore, MD'", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;UACE10 UACE10 VISIBLE NONE;AFFGEOID10 AFFGEOID10 VISIBLE NONE;GEOID10 GEOID10 VISIBLE NONE;NAME10 NAME10 VISIBLE NONE;NAMELSAD10 NAMELSAD10 VISIBLE NONE;LSAD10 LSAD10 VISIBLE NONE;UATYP10 UATYP10 VISIBLE NONE;ALAND10 ALAND10 VISIBLE NONE")

		print "Area clip of Census Tracts"
		# Process: Clip (2)
		arcpy.Clip_analysis(state_tracts_clip_shp, urban_area, urban_area_tracts_shp, "")

except:
	print arcpy.GetMessages()